# 128 quotes from EB. These are displayed on the About EBME window. Just for fun.
# Can you get the 1/128 Sword of kings?

import random


def getRandomQuote() -> tuple[str, bool]:
    quote = random.choice(QUOTES)
    if quote in SATURNQUOTES:
        return quote, True
    return quote, False

SATURNQUOTES = ("Hi ho. Me Mr. Saturn.", "We look like same!")

QUOTES = (
"(It's Escargo Express's neglected class.)",
"(You listened to my advice and fought courageously. You rock!)",
"...Brick Road.",
"...My name? Let's say, Flying Man.",
"...You should thank me. That Diamond is worth maybe...MAYBE...$50.",
"&lt;Can I have your autograph?&gt; is an airheaded question. I won't ask you for it.",
"&lt;No, no! We can't! This baby is a demon child!&gt;",
"After all, it could only cost you your life, and you got that for free!",
"Are you just here to say &lt;Hi&gt;? What a loser!",
"As strange as this may sound, there are statues of rabbits blocking your way.",
"At this point, you guys just might be the strongest force in the world, don't you think?",
"At times like this, kids like you should be playing Nintendo games.",
"Besides humans, dogs also sleep at night. Why aren't you asleep?",
"But because of the loan, my family and I now live in poverty!",
"But remember, we are best friends forever.",
"By using the Insignificant Present, you had a very fruitful experience that cannot be understood by someone who does not use something insignificant.",
"Cows and carrots?... That's a nutty combination!",
"Do you know whose bones are on display here?",
"Don't spit your gum out. Even if it has lost its flavour...",
"Don't talk to me. My mind is a complete blank.",
"Don't you think that's an incredibly masculine taunt to throw at you?",
"Except I don't have any money to play the games...",
"Finally, I can measure my own tail!",
"For some reason, a pencil-shaped iron statue is blocking the path.",
"Free your mind and KNOW what you must do!",
"Good. That may be the best choice.",
"Hang on! That's way too cool to just throw away! Keep it!",
"Hello! And... good-bye!",
"Hello! Mach Pizza delivery! Here is your pizza pie, sir.",
"Hey Ness! You're just here to bother me, aren't you.",
"Hey dudes! It's summer! It's the manly time of year! Time for sports, guys!",
"Hey, sidewalk! Get out of my way!",
"Hi ho. Me Mr. Saturn.",
"I always eat garlic and work out to make my body stronger.",
"I am going to try to be the first to get there...",
"I am your courage. I follow you here in Magicant.",
"I believe I'm the third strongest amongst us. Take your best shot!",
"I don't care if everyone thinks I'm a stubborn mutt.",
"I have no patience when people interrupt me while I'm busy doing nothing.",
"I threw my slippers at the beast... Maybe you didn't notice.",
"I understand your point about the fate of the world being at stake.",
"I used all leftover materials. This is a very special Magic cake!",
"I want to tell you the story of the creature from the vegetable soup.",
"I'll demonstrate the power of being third to you!",
"I'm going to tell you something very important. You may want to take notes. Ready? ......You're the chosen one.",
"I'm really the third strongest master. I'll destroy you now!",
"If I keep talking about unrelated stuff, you might start ignoring important messages.",
"It could never happen! ...Well, actually that's not true.",
"It may be none of my business, but don't you think it would be a good idea if you took a break?",
"It will always bring back the fondest of memories...",
"It's been a long time, Buzz Buzz.",
"It's been maybe 10 years since I last saw you.",
"It's strange and marvelous...as well as mysterious...ooooo!...",
"Just remember, I'm always behind you 100%. Don't be afraid.",
"Kids can borrow only maps at this library.",
"Last night there was a solitare tournament. ...I lost my shirt....",
"Let's break into the room next door...'Cept I need to go to the bathroom first...",
"Let's just pretend that you're Ness, and I'll give this to you.",
"My strength falls between the second and fourth strongest masters.",
"Ness briefly had a vision of a baby in a red cap.",
"Ness caught a glimpse of a small, cute puppy.",
"Ness caught a whiff of Steak, but just for a second.",
"Ness dug around in the trash can. Well, let's see here...",
"Ness had a short vision of seeing his mother when she was young.",
"Ness had the feeling that he was being watched by himself as a baby.",
"Ness saw a baby's bottle, but just for an instant.",
"Ness saw a vision of his father holding him.",
"Ness thought he heard his mother from far away... she said &lt;Be a thoughtful, strong boy...&gt;",
"Ness touched the Sound Stone to his forehead and gathered his thoughts.",
"Ness! Now, I...well...It's going to seem like I'm running away...",
"No problem here.",
"Now you see the true advantage of being third!",
"OK, pop quiz! &lt;A Beatles song, XXXterday.&gt; Can you fill in the blanks?",
"Okay, get ready for an instant memory!",
"Onett police are infamous for closing roads if something is going on.",
"Onett police chief finishes EarthBound, asks, &lt;Where is the sequel?&gt;",
"Paula prayed from the bottom of her heart.",
"Pictures taken instantaneously!",
"Remember to &lt;Go for it!&gt;",
"SECRET CODE, PLEASE. SAY YOUR CODE IN 10 SECONDS.",
"Say, fuzzy pickles!",
"Second Floor - &lt;Second Floor of the Bakery&gt;",
"Since you left home on your journey, things have changed around here. For example, I don't have as much laundry.",
"Sorry about giving you this game-type advice, but you should equip your weapon!",
"Spankety spankety spankety!",
"TAAAAAH-DAAAAAH!",
"Thank you for taking the time to talk to me again.",
"Thanks, game player! Thank you very much!",
"That banana peel has an authentic &lt;Venus&gt; autograph?",
"That's just fine, but...",
"That's my real job, you know...I'm a billboard guy.",
"That's right, you--the one holding the controller.",
"The city will soon be in worse condition than living in your own puke!",
"The war against Giygas is over...",
"There is no turning back now...",
"There is only one seat, so you can't ride the bike now.",
"There was just plain ol' garbage in the trash can.",
"They never ask me &lt;Would you like fries with that shake?&gt;",
"This department store is gonna be your grave! Gwaaagh.",
"This helicopter will really come in handy.",
"This is the first &lt;Your Sanctuary&gt; location. But it's mine now.",
"This little nipper took us from a nightmare to a dream...",
"This mouse loves you.",
"To meet Geldegarde Monotoli, you'll need our help.",
"Try to keep as healthy as possible, even if it kills you!",
"Uh, I'vegotsomeproblemsheregottago, bye!",
"WHOAAAAAAAAAAH!",
"We had fun one snowy day. I melted, but I am still real in your memory.",
"We look like same!",
"We're known as the &lt;Tessie-Watching Club&gt;.",
"Wecome home, Ness.",
"Wel come to moo nsi ns dem oons ide.",
"Well, I'd better go, I think my omlette might be on fire! Bye!",
"When on your way out<br>Be sure that you say goodbye<br>Then lock the door tight.",
"When you get to the hotel, be sure to give your dear ol' dad a call.",
"Who are you talking to?",
"Wow, what a great photograph!",
"Yesno, you will won't.",
"You cannot teleport while Dungeon Man is with you.",
"You guys can't envision the final collapse of capitalism? Incredible!",
"You have too much stuff.",
"You should wait to teleport until after Escargo Express arrives.",
"You should wait to teleport until after a customer has shown up.",
"You should wait to teleport until after the pizza arrives.",
"You will be gone, and you'll be burning in...well, you'll go to heaven!",
"You're the enemy of all zombies! You monster!",
"Your dear old dad was also thinking about hitting the hay for the night.",
"Your existence is a problem for me and my religion.",

"Inside the present, there was a Sword of kings!",
)